// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bv2RKWYiWr8XrYtTFTaGkZ5iff_AcxI',
    appId: '1:302829653977:web:b27c31b67b19e2b1aad3c8',
    messagingSenderId: '302829653977',
    projectId: 'unboarding-tm-402908',
    authDomain: 'unboarding-tm-402908.firebaseapp.com',
    storageBucket: 'unboarding-tm-402908.appspot.com',
    measurementId: 'G-RQC6DC9BWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoz1Bc1A7r50ysXiHyJK-1BN0_kgbNxhQ',
    appId: '1:302829653977:android:506d1acc9000da21aad3c8',
    messagingSenderId: '302829653977',
    projectId: 'unboarding-tm-402908',
    storageBucket: 'unboarding-tm-402908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZs4xLjl42ml4j6ITHS2-y6de1h5mrPjU',
    appId: '1:302829653977:ios:7f3500911032bf28aad3c8',
    messagingSenderId: '302829653977',
    projectId: 'unboarding-tm-402908',
    storageBucket: 'unboarding-tm-402908.appspot.com',
    iosBundleId: 'com.example.onboardingTm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZs4xLjl42ml4j6ITHS2-y6de1h5mrPjU',
    appId: '1:302829653977:ios:77d20e53aca963f5aad3c8',
    messagingSenderId: '302829653977',
    projectId: 'unboarding-tm-402908',
    storageBucket: 'unboarding-tm-402908.appspot.com',
    iosBundleId: 'com.example.onboardingTm.RunnerTests',
  );
}
